[package]
authors = ["Saghm Rossi <saghmrossi@gmail.com>"]
description = "MongoDB version manager"
edition = "2018"
license = "Apache-2.0"
name = "monger"
repository = "https://github.com/saghm/monger"
version = "0.9.0"
readme = "README.md"

[dependencies]
clap = "2.33.0"
monger-core = "0.9.0"
